spring:
  r2dbc:
    url: r2dbc:h2:file:///./tmp/test-database
    username: sa
    password:
  main:
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:/db/migration
    url: jdbc:h2:file:./tmp/test-database
    user: sa
    password:
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
