spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./tmp/mydb
    username: sa
    password: sa
  flyway:
    enabled: true
    locations: classpath:/db/migration
server:
  port: 80

# UserConfig properties
person:
  name: Maxim
  age: 45


---
spring:
  profiles: "test"
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:h2:mem:test