spring:
  r2dbc:
    url: r2dbc:h2:file:///./tmp/test-database
    username: sa
    password:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    url: jdbc:h2:file:./tmp/test-database
    user: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 80

---
#spring:
#  profiles: "test"
#  main:
#    lazy-initialization: true
#  datasource:
#    url: jdbc:h2:mem:test
